services:
  dbt:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app/.venv/bin/python
      - PYDEVD_DISABLE_FILE_VALIDATION=1
    command: "tail -f /dev/null"
